# A sample workflow which checks out the code for suggestions
# using Reliably.
# The results are then uploaded to GitHub Security Code Scanning.

name: Reliably workflow
on: push

jobs:
  k8s-code-scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reliablyhq/actions/scan@v1
        env:
          RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}
          RELIABLY_ORG: ${{ secrets.RELIABLY_ORG }}
        continue-on-error: true
        with:
          service: my awesome service
          type: build
          outcome: success
