name: Reliably workflow
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: reliablyhq/actions/setup@v1
      - uses: reliablyhq/actions/status@v1
        env:
          RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}
          RELIABLY_ORG: ${{ secrets.RELIABLY_ORG }}
        with:
          selector: app=payment
